@startuml

title __IMPL's Class Diagram__\n

  package ua.training.model.dao {
    package ua.training.model.dao.impl {
      class ArticleDaoJDBC {
          - connection : Connection
          + ArticleDaoJDBC()
          + create()
          + findById()
          + findAll()
          + findByPeriodical()
          + findByPeriodicalFixedNumberOfArticles()
          + update()
          + delete()
          + close()
          + setAutoCommit()
          + rollback()
      }
    }
  }
  

  package ua.training.model.dao {
    package ua.training.model.dao.impl {
      class PaymentDaoJDBC {
          - connection : Connection
          + PaymentDaoJDBC()
          + create()
          + findById()
          + findAll()
          + findByUser()
          + findByPeriodical()
          + update()
          + delete()
          + close()
          + setAutoCommit()
          + rollback()
      }
    }
  }
  

  package ua.training.model.dao {
    package ua.training.model.dao.impl {
      class PeriodicalDaoJDBC {
          - connection : Connection
          + PeriodicalDaoJDBC()
          + create()
          + findById()
          + findAll()
          + findByUser()
          + findByPayment()
          + findFixedNumberOfPeriodicals()
          + searchPeriodicals()
          + update()
          + delete()
          + close()
          + setAutoCommit()
          + rollback()
      }
    }
  }
  

  package ua.training.model.dao {
    package ua.training.model.dao.impl {
      class UserDaoJDBC {
          - connection : Connection
          + UserDaoJDBC()
          + findByLogin()
          + create()
          + findById()
          + findAll()
          + updateMoney()
          + findByPeriodical()
          + update()
          + delete()
          + close()
          + setAutoCommit()
          + rollback()
      }
    }
  }
  

  ArticleDaoJDBC -up-|> ArticleDao
  PaymentDaoJDBC -up-|> PaymentDao
  PeriodicalDaoJDBC -up-|> PeriodicalDao
  UserDaoJDBC -up-|> UserDao


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
